### PR TITLE
Trigger jobs also when Runs (Builds) are deleted

### PR DESCRIPTION
**Pull request by thomasfox**
If a jenkins pipeline job creates external artifacts, e.g. pushes a docker image to a docker registry, it can be useful if jenkins removes these artifacts when a run (aka build) is deleted. For this scenario, this pull requests adds the possibility to trigger jenkins jobs when a run is deleted. The triggered jobs can then cleanup the external artifacts associated with the run.

I have left the code structure as close to the existing code structure as needed. Ping me if you would appreciate more refactoring.

Also documentation is missing for now. If you find the supplied feature useful, I can update it.

### CODE REVIEW

**Comment by aytuncbeken** [comment]
Thanks for the contribution, I need to test this and understand how it works in details. For summary, what I understand is, When the run/build is deleted from branch job, this job will be triggered. right ?

**Comment by aytuncbeken** [comment]
And there are some conflicts in the code, I will be glad if you can solve them.

**Comment by thomasfox** [comment]
Your understanding is correct.
I'll have a go at the conficts today or tomorrow.

**Comment by thomasfox** [comment]
I solved the conflicts in the pull request.

**Comment by aytuncbeken** [comment]
Everything seems fine. Thanks for the contribution. I will release and let you know.

**Comment by aytuncbeken** [comment]
AutoComplete was missing in the filed, added.  Fyi

**Comment by aytuncbeken** [comment]
Released with 1.7

**Comment by thomasfox** [comment]
Thanks for merging. Should I then update the documentation? The new field is missing in the screenshots at least.

**Comment by aytuncbeken** [comment]
That will be great. Thanks.

**Pull request merged**
