### PR TITLE
Fix parameter duplication

### LINKED ISSUE #39: Job Configuration grows every run
**Describe the bug**
When a job is run, a new ParametersDefinitionProperty is appended to the job instead of replacing any existing ones.  This causes the job config to grow infinitely large.

**To Reproduce**
Trigger a job using this plugin.

**Expected behavior**
The MultiBranch Action Triggers parameters are added if and only if they are missing.

**Screenshots**
A small excerpt from our job:
<details>

```xml
    <hudson.model.ParametersDefinitionProperty>
      <parameterDefinitions class="java.util.Arrays$ArrayList">
        <a class="hudson.model.ParameterDefinition-array">
          <hudson.model.StringParameterDefinition>
            <name>SOURCE_PROJECT_NAME</name>
            <description>Added by MultiBranch Pipeline Plugin</description>
            <defaultValue>This will be set by MultiBranch Pipeline Plugin</defaultValue>
            <trim>false</trim>
          </hudson.model.StringParameterDefinition>
          <hudson.model.StringParameterDefinition>
            <name>SOURCE_PROJECT_FULL_NAME</name>
            <description>Added by MultiBranch Pipeline Plugin</description>
            <defaultValue>This will be set by MultiBranch Pipeline Plugin</defaultValue>
            <trim>false</trim>
          </hudson.model.StringParameterDefinition>
          <hudson.model.StringParameterDefinition>
            <name>SOURCE_BRANCH_NAME</name>
            <description>Added by MultiBranch Pipeline Plugin</description>
            <defaultValue>This will be set by MultiBranch Pipeline Plugin</defaultValue>
            <trim>false</trim>
          </hudson.model.StringParameterDefinition>
          <hudson.model.StringParameterDefinition>
            <name>TARGET_BRANCH_NAME</name>
            <description>Added by MultiBranch Pipeline Plugin</description>
            <defaultValue>This will be set by MultiBranch Pipeline Plugin</defaultValue>
            <trim>false</trim>
          </hudson.model.StringParameterDefinition>
          <hudson.model.StringParameterDefinition>
            <name>SOURCE_RUN_NUMBER</name>
            <description>Added by MultiBranch Pipeline Plugin</description>
            <defaultValue>This will be set by MultiBranch Pipeline Plugin</defaultValue>
            <trim>false</trim>
          </hudson.model.StringParameterDefinition>
          <hudson.model.StringParameterDefinition>
            <name>SOURCE_RUN_DISPLAY_NAME</name>
            <description>Added by MultiBranch Pipeline Plugin</description>
            <defaultValue>This will be set by MultiBranch Pipeline Plugin</defaultValue>
            <trim>false</trim>
          </hudson.model.StringParameterDefinition>
        </a>
      </parameterDefinitions>
    </hudson.model.ParametersDefinitionProperty>
    <hudson.model.ParametersDefinitionProperty>
      <parameterDefinitions class="java.util.Arrays$ArrayList">
        <a class="hudson.model.ParameterDefinition-array">
          <hudson.model.StringParameterDefinition>
            <name>SOURCE_PROJECT_NAME</name>
            <description>Added by MultiBranch Pipeline Plugin</description>
            <defaultValue>This will be set by MultiBranch Pipeline Plugin</defaultValue>
            <trim>false</trim>
          </hudson.model.StringParameterDefinition>
          <hudson.model.StringParameterDefinition>
            <name>SOURCE_PROJECT_FULL_NAME</name>
            <description>Added by MultiBranch Pipeline Plugin</description>
            <defaultValue>This will be set by MultiBranch Pipeline Plugin</defaultValue>
            <trim>false</trim>
          </hudson.model.StringParameterDefinition>
          <hudson.model.StringParameterDefinition>
            <name>SOURCE_BRANCH_NAME</name>
            <description>Added by MultiBranch Pipeline Plugin</description>
            <defaultValue>This will be set by MultiBranch Pipeline Plugin</defaultValue>
            <trim>false</trim>
          </hudson.model.StringParameterDefinition>
          <hudson.model.StringParameterDefinition>
            <name>TARGET_BRANCH_NAME</name>
            <description>Added by MultiBranch Pipeline Plugin</description>
            <defaultValue>This will be set by MultiBranch Pipeline Plugin</defaultValue>
            <trim>false</trim>
          </hudson.model.StringParameterDefinition>
          <hudson.model.StringParameterDefinition>
            <name>SOURCE_RUN_NUMBER</name>
            <description>Added by MultiBranch Pipeline Plugin</description>
            <defaultValue>This will be set by MultiBranch Pipeline Plugin</defaultValue>
            <trim>false</trim>
          </hudson.model.StringParameterDefinition>
          <hudson.model.StringParameterDefinition>
            <name>SOURCE_RUN_DISPLAY_NAME</name>
            <description>Added by MultiBranch Pipeline Plugin</description>
            <defaultValue>This will be set by MultiBranch Pipeline Plugin</defaultValue>
            <trim>false</trim>
          </hudson.model.StringParameterDefinition>
        </a>
      </parameterDefinitions>
    </hudson.model.ParametersDefinitionProperty>
    <hudson.model.ParametersDefinitionProperty>
      <parameterDefinitions class="java.util.Arrays$ArrayList">
        <a class="hudson.model.ParameterDefinition-array">
          <hudson.model.StringParameterDefinition>
            <name>SOURCE_PROJECT_NAME</name>
            <description>Added by MultiBranch Pipeline Plugin</description>
            <defaultValue>This will be set by MultiBranch Pipeline Plugin</defaultValue>
            <trim>false</trim>
          </hudson.model.StringParameterDefinition>
          <hudson.model.StringParameterDefinition>
            <name>SOURCE_PROJECT_FULL_NAME</name>
            <description>Added by MultiBranch Pipeline Plugin</description>
            <defaultValue>This will be set by MultiBranch Pipeline Plugin</defaultValue>
            <trim>false</trim>
          </hudson.model.StringParameterDefinition>
          <hudson.model.StringParameterDefinition>
            <name>SOURCE_BRANCH_NAME</name>
            <description>Added by MultiBranch Pipeline Plugin</description>
            <defaultValue>This will be set by MultiBranch Pipeline Plugin</defaultValue>
            <trim>false</trim>
          </hudson.model.StringParameterDefinition>
          <hudson.model.StringParameterDefinition>
            <name>TARGET_BRANCH_NAME</name>
            <description>Added by MultiBranch Pipeline Plugin</description>
            <defaultValue>This will be set by MultiBranch Pipeline Plugin</defaultValue>
            <trim>false</trim>
          </hudson.model.StringParameterDefinition>
          <hudson.model.StringParameterDefinition>
            <name>SOURCE_RUN_NUMBER</name>
            <description>Added by MultiBranch Pipeline Plugin</description>
            <defaultValue>This will be set by MultiBranch Pipeline Plugin</defaultValue>
            <trim>false</trim>
          </hudson.model.StringParameterDefinition>
          <hudson.model.StringParameterDefinition>
            <name>SOURCE_RUN_DISPLAY_NAME</name>
            <description>Added by MultiBranch Pipeline Plugin</description>
            <defaultValue>This will be set by MultiBranch Pipeline Plugin</defaultValue>
            <trim>false</trim>
          </hudson.model.StringParameterDefinition>
        </a>
      </parameterDefinitions>
    </hudson.model.ParametersDefinitionProperty>
```
</details>
The whole file is 402,147 lines and growing.

### PR DESCRIPTION
**Pull request by niraami**
Closes #39 
I've added checks to `setJobParameters` to make sure the parameters don't already exist before adding them.

### Testing done

Tests pass, spotbugs passes, and I've tested it on our Jenkins instance.
I've tested the following things:
- Using it on a completely new pipeline (adds parameters just fine)
- Subsequent runs don't create new parameters
- Using it on an existing pipeline, whose parameters were configured beforehand

### Submitter checklist
- [x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [x] Link to relevant issues in GitHub or Jira
- [ ] Link to relevant pull requests, esp. upstream and downstream changes
- [x] Ensure you have provided tests - that demonstrates feature works or fixes the issue

### CODE REVIEW

**Comment by niraami** [comment]
Could this be merged? I believe I've done everything I could to make it as simple for you as possible. Also, I've been running a custom built plugin with this fix in our Jenkins for a while now, no issues so far.
@aytuncbeken

**Comment by niraami** [comment]
If the code coverage is the deal-breaker holing this PR back, let me know, I can look into it. I'm just super unfamiliar with Java coverage tests, that's why I didn't do that just yet.

> 4 lines are not covered
> 1 line is covered only partially

**Review by aytuncbeken — APPROVED** [review]

**Comment by aytuncbeken** [comment]
Looks good. Thank for fixing it.

**Comment by aytuncbeken** [comment]
Hey @niraami 
It will be released with 1.8.12 version

**Pull request merged**
