### PR TITLE
set job param property when job is triggered

### PR DESCRIPTION
**Pull request by runzexia**
Signed-off-by: runzexia <runzexia@yunify.com>

We created the job using xml, which caused the Job parameter to not be properly set.
I also check if the parameter exists, if it does not exist, add it, making xml parsing easier.

### CODE REVIEW

**Comment by runzexia** [comment]
@aytuncbeken

**Comment by aytuncbeken** [comment]
Thanks for the contribution.

**Comment by runzexia** [comment]
@aytuncbeken Could you help create a release?

**Comment by aytuncbeken** [comment]
Sure, released with version 1.4.

**Pull request merged**
